using System.Text;
using HydraScript.Domain.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace HydraScript.Infrastructure.LexerRegexGenerator;

[Generator(LanguageNames.CSharp)]
public class PatternGenerator : IIncrementalGenerator
{
    public ITokenTypesStreamProvider Provider { get; init; } = new DefaultTokenTypesStreamProvider();

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tokenTypes = Provider.TokenTypesStream
            .OrderBy(x => x.Priority)
            .Concat([new TokenTypes.Dto("ERROR", @"\S+", int.MaxValue)]);
        var pattern = string.Join("|", tokenTypes.Select(t => $"(?<{t.Tag}>{t.Pattern})"));

        var code = $@"// <auto-generated/>

using System.Diagnostics.CodeAnalysis;

namespace HydraScript.Infrastructure;

internal partial class PatternContainer
{{
    [StringSyntax(StringSyntaxAttribute.Regex)]
    public const string Value = """"""{pattern}"""""";
}}
";

        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "PatternContainer.g.cs",
            SourceText.From(code, Encoding.UTF8)));
    }
}